---
title: Interactive clothing networks
author: Allen Chang
date: '2018-01-30'
slug: interactive-clothing-networks
categories: []
tags:
  - networks
  - visualization
  - R
  - clothing
draft: yes
---

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(tidyverse)
library(igraph)
library(threejs)
library(lubridate)
library(stringr)
library(reshape2)
library(htmlwidgets)
library(RColorBrewer)
library(gganimate)
```

```{r}
summer <- read_csv("/Users/allenchang/Desktop/functionally_defined/data/summer.csv")
fw <- read_csv("/Users/allenchang/Desktop/functionally_defined/data/fallwinter.csv")

fw <- fw %>%
  select(1:3)

clothes_df <- rbind(summer, fw)
clothes_df$Day <- mdy(clothes_df$Day)
```

```{r}
clothes_df <- clothes_df %>%
  mutate(maker_up = toupper(Maker)) %>%
  select(Day, maker_up) %>%
  filter(!maker_up == "NA")

clothes_mat <- clothes_df %>%
  acast(maker_up ~ Day, fun.aggregate = length)

cooccur <- clothes_mat %*% t(clothes_mat)

g <- graph.adjacency(cooccur, weighted = TRUE, mode = "undirected", diag = FALSE)
```

```{r}
V(g)$vertex_degree <-  degree(g)
```

```{r}
counts <- as.data.frame(lengths(as_adj_list(g))) %>%
  rownames_to_column()

names(counts) <- c("maker", "count")
counts <- counts %>%
  filter(count < 10)

g2 <- delete_vertices(g, counts$maker)
```


```{r}
country <- as.factor(c("USA", "United Kingdom", "Japan", "Japan", "USA", "USA", "South Korea", "Belgium", "Japan", "Italy", "Austria", "France", "Japan", "USA", "Germany", "Belgium", "France", "France", "France", "USA", "USA", "Sweden", "Canada", "Germany", "Japan", "Belgium", "Japan", "Japan", "USA"))

# V(g)$country <- country

########## WIP
# country <- c("USA", "Japan", "USA", "South Korea", "Belgium",
#              "Italy", "Austria", "France", "Japan", "France",
#              "France" , "USA", "Japan", "Belgium", "Japan",
#              "Japan", "USA")

 scheme <- c("#A60C00", "#1533AD", "#A60C00", "#7109AA", "#A63C00",
             "#007B25", "#009999", "#CB0077", "#1533AD", "#CB0077",
             "#CB0077", "#A60C00", "#1533AD", "#A63C00", "#1533AD",
             "#1533AD", "#A60C00")


# V(g)$color <- as.factor(country)
```


```{r}
graphjs(g2, 
        repulsion = 6, 
        vertex.shape = "sphere",
        vertex.size = V(g2)$vertex_degree*.5,
        vertex.label= V(g2)$name,
        stroke = TRUE,
        curvature = 0.2,
        vertex.color = scheme)
        # vertex.color = palpair)
        
```

```{r fig.height=11, fig.width=8}

h <- hclust(dist(clothes_mat, method = "canberra"))

ordering <- h$labels[h$order]

day_vis <- clothes_df %>%
  ungroup() %>%
  mutate(maker = factor(maker_up, levels = ordering)) 

p <- ggplot(day_vis, aes(Day, maker)) +
  geom_path(aes(group = Day)) +
  geom_point(aes(frame = Day), color = "red", size = 3) +
  geom_vline(aes(xintercept = as.numeric(Day), frame = as.numeric(Day)), lty = 2, color = "black") + theme_bw()

gganimate(p, ani.width = 600, ani.height = 900)
```


### References

[vertex size](https://stackoverflow.com/questions/40181355/network-graph-using-r-node-size-based-on-number-of-connected-edges)

[setting vertex attributes](https://stackoverflow.com/questions/36851569/import-of-vertices-attributes-in-igraph-in-r)